ProEmbV4/Models/BlogDataContext.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using MySql.Data.EntityFrameworkCore.Extensions;
using MySql.Data.MySqlClient;

namespace ProEmbV4.Models
{
    //public class BlogDataContext:DbContext
    //{

    //    public DbSet<Post> Posts { get; set;}

    //    public BlogDataContext(DbContextOptions<BlogDataContext> options)
    //        :base(options)
    //    {
    //        Database.EnsureCreated();
    //    }


    //}

}

ProEmbV4/Models/FormattingService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProEmbV4.Models
{
    public class FormattingService
    {
        public string AsReadableDate(DateTime date)
        {
            return date.ToString("D");
        }
    }
}

ProEmbV4/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace ProEmbV4.Models
{
    public class Post
    {
        public long Id { get; set; }
        private string _key;

        public string Key
        {
            get
            {
                if (_key == null)
                {
                    _key = Regex.Replace(Title.ToLower(), "[^a-z0-9]", "-");
                }

                return _key;
            }
            set { _key = value; }
        }
        [Display(Name ="Post Title")]
        [Required]
        [DataType(DataType.Text)]
        [StringLength(100,MinimumLength = 5, ErrorMessage = "Title must be between 5 & 100 chars long")]
        public string Title { get; set; }

        public string Author { get; set; }
        [Required]
        [MinLength(100, ErrorMessage = "Blog posts must be between 5 & 100 chars long")]
        [DataType(DataType.MultilineText)]
        public string Body { get; set; }
        public DateTime Posted { get; set; }
    }
}

ProEmbV4/Models/UsedModelsDataContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProEmbV4.Models
{
    public class UsedModels
    {
        public string Key { get; internal set; }
        public string Name { get; internal set; }
        public string Type { get; internal set; }

    }
    public class UsedModelsDataContext
    {
        public IEnumerable<UsedModels> GetUsedModels()
        {
            return new[]
            {
                new UsedModels {
                    Key = "LoraWan",
                    Name = "Draadloze Communicatie",
                    Type = "LoraWan",
                    
                },
                new UsedModels {
                    Key = "TC74",
                    Name = "Temperatuur Meting",
                    Type = "TC74",
                    
                },
                new UsedModels {
                    Key = "Webcam",
                    Name = "Webcam Embedded",
                    Type = "Webcam",
                    
                },
                new UsedModels {
                    Key = "Relais",
                    Name = "Relais Embedded",
                    Type = "Relais",
                    
                },
            };
        }
    }
}

ProEmbV4/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProEmbV4.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ProEmbV4.Controllers
{
    [Route("blog")]
    public class BlogController : Controller
    {
        //private readonly BlogDataContext _db;

        //public BlogController(BlogDataContext db)
        //{
        //    _db = db;
        //}
        [Route("")]
        public IActionResult Index()
        {
            var posts = new[]
            {
                new Post
                {
                     Title = "My blog post",
                Posted = DateTime.Now,
                Author = "Jelle",
                Body = "Mooi hoor.",
                },
                new Post
                {
                     Title = "My blog post",
                Posted = DateTime.Now,
                Author = "Laurens",
                Body = "Jammer genoeg niet op de pi...",
                },
            };
            return View(posts);
        }
        [Route("{year:min(2017)}/{month:range(1,12)}/{key}")]
        public IActionResult Post(int year,int month,string key)
        {
            var post = new Post
            {
                Title = "My blog post",
                Posted = DateTime.Now,
                Author = "Michiel",
                Body = "Lorawan is gemakkelijk",
            };
            return View(post); //post
        }
        [HttpGet,Route("create")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost,Route("create")]
        public IActionResult Create(Post post)
        {
            if (!ModelState.IsValid)
                return View();
            post.Author = User.Identity.Name;
            post.Posted = DateTime.Now;

            //_db.Posts.Add(post);
            //_db.SaveChanges();
            return View();
        }


    }
}

ProEmbV4/Controllers/DynamoDBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web.Helpers;
using DynamoDbLibs.DynamoDB;
using DynamoDbLibs.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.TagHelpers;

namespace ProEmbV4.Controllers
{
    [Produces("application/json")]
    [Route("api/DynamoDB")]
    public class DynamoDBController : Controller
    {
        private readonly IGetItem _getItem;

        public DynamoDBController(IGetItem getItem)
        {
            _getItem = getItem;
        }

        [Route("getSomeItems")]
        public async Task<IActionResult> GetSomeItems([FromQuery] string dev_id)
        {
            var response = await _getItem.GetSomeItems(dev_id);


            return Ok(response);
        }

        [Route("getAllItems")]
        public async Task<IActionResult> GetAllItems()
        {
            var response =  await _getItem.GetAllItems();
            
            //return Ok(response);
            return View(response);
        }
    }
}

ProEmbV4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Helpers;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ProEmbV4.Controllers
{
    public class HomeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

ProEmbV4/Controllers/WebcamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProEmbV4.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ProEmbV4.Controllers
{
    [Route("webcam")]
    public class WebcamController : Controller
    {
        [HttpGet, Route("webcam")]
        public IActionResult Webcam()
        {
            return View();
        }
    }
}

ProEmbV4/ViewComponents/UsedModelsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ProEmbV4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProEmbV4.ViewComponents
{
    [ViewComponent]
    public class UsedModelsViewComponent : ViewComponent
    {
        private readonly UsedModelsDataContext _usedModels;

        public UsedModelsViewComponent(UsedModelsDataContext usedModels)
        {
            _usedModels = usedModels;
        }
        public IViewComponentResult Invoke()
        {
            var usedModels = _usedModels.GetUsedModels();
            return View(usedModels);
        }
    }
}

ProEmbV4/Views/Blog/Create.cshtml
@model ProEmbV4.Models.Post
@{
    Layout = "_Layout";
}

<h1>Create Blog Post</h1>
<fieldset>
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary()
        <p>
            @Html.LabelFor(x => x.Title)
            @Html.EditorFor(x => x.Title)
            @Html.ValidationMessageFor(x => x.Title)
        </p>
        <p>
            @Html.LabelFor(x => x.Body)
            @Html.EditorFor(x => x.Body)
            @Html.ValidationMessageFor(x => x.Body)
        </p>
        <p>
        <button type="submit">Create Post</button>
        </p>
    }
</fieldset>

ProEmbV4/Views/Blog/Index.cshtml
@model IEnumerable<ProEmbV4.Models.Post>
@{ 
    Layout = "_SimpleLayout";
}

<div class="blog-posts">
    @foreach (var post in Model)
    {
          @Html.Partial("_Post", post)
    }
</div>

ProEmbV4/Views/Blog/Post.cshtml
@model  ProEmbV4.Models.Post
@{ 
    Layout = "_SimpleLayout";
}

@Html.Partial("_Post")

ProEmbV4/Views/DynamoDB/GetAllItems.cshtml
@using DynamoDbLibs.DynamoDB
@using Newtonsoft.Json
@model DynamoDbLibs.Models.DynamoTableItems

@{
    Layout = "_Layout";
}

<h1>Tabel dynamoDB</h1>
<table id="DynamoDB">
    <tr>
        <th>dev_id</th>
        <th>time</th>
        <th>temperature</th>
    </tr>
    @for (var i = 0; i < @Model.Items.Count(); i++)
    {
        var b = Convert.FromBase64String(@Model.Items.ElementAt(i).temperature);

        var TempHex = BitConverter.ToString(b);

        int Temp = Convert.ToInt32(TempHex, 16);
        <tr>
            <div class="details">
                <td>@Model.Items.ElementAt(i).dev_id</td>
                <td>@Model.Items.ElementAt(i).time</td>
                <td>@Temp</td>
            </div>
        </tr>
    }
</table>

<div id="graph"></div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script type="text/javascript">
    // Load google charts
    google.charts.load('current', { 'packages': ['corechart'] });
    google.charts.setOnLoadCallback(drawChart);

    // Draw the chart and set the chart values
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['time', 'temperature'],
            ["2018-05-24T13:01:25", 28],
            ["2018-05-24T13:01:30", 28],
            ["2018-05-24T13:01:36", 28],
            ["2018-05-24T13:01:41", 28],
            ["2018-05-24T13:01:46", 28]
        ]);

        var options = {
            title: 'tc74 temperature',
            curveType: 'function',
            legend: { position: 'left' }
        };


        // Display the chart inside the <div> element with id="graph"
        var chart = new google.visualization.LineChart(document.getElementById('graph'));
        chart.draw(data, options);
    }
</script>

ProEmbV4/Views/Home/index.cshtml
@{
    Layout = "_Layout";
}



<article id="mainArticle">
    <h1>Project µC & Embedded</h1>
    <p class="spotlight">
    Welkom tot onze site.<br/>
</article>

ProEmbV4/Views/Shared/Components/UsedModels/Default.cshtml
@model IEnumerable<ProEmbV4.Models.UsedModels>
<h1>Gebruikte Modules</h1>

@foreach (var usedModel in Model)
{
    <h2 class="top">
        <img src="/images/@(usedModel.Key).gif" alt="@usedModel.Name" width="75" height="75">
        
    </h2>
    <p>
        @usedModel.Type <br>
        <a href="/tours/@(usedModel.Key).htm"></a>
    </p>
}

ProEmbV4/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Welcome Laurens & Michiel Project µC & Embedded</title>
<!--make sure mobile devices display the page at the proper scale	-->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<link href="/css/main.css" rel="stylesheet" type="text/css" media="screen, projection">
</head>
<body id="home" class="no-js">
<div id="wrapper">
  <header id="mainHeader"> <a href="/" title="home" class="logo">
   <!-- I need this div because IE is an affront to mankind-->
   <div>
    <h1>Project µC & Embedded</h1>
     </div>
    </a>
    <nav id="siteNav">
      <h1>Where do you want to go?</h1>
      <ul>
       <li><a href="@Url.Action("GetAllItems","DynamoDB")" title="Temperatuur via LoraWan">Temperatuur<br /><span class="tagline">Temperatuur via LoraWan</span></a>
        </li>
        <li><a href="@Url.Action("Webcam","Webcam")"  title="Can you see?">Webcam <br /><span class="tagline">Webcam point of view</span></a></li>
       @*<li><a href="resources.htm" title="Stuur de relais aan!">Relais<br /><span class="tagline">Relais aansturing</span></a>
          <ul>
            <li><a href="resources/faq.htm" title="Got questions?">Tour FAQs</a></li>
            <li><a href="resources/additional_resources.htm" title="additional resources">Tour Information</a></li>
            <li><a href="resources/terms.htm" title="terms and conditions">Site Terms</a></li>
          </ul>*@
        @*</li>*@
        <li><a href="@Url.Action("Index","Blog")" title="Our community">Blog <br /><span class="tagline">join our community</span></a>
        </li>
        @*<li><a href="contact.htm" title="contact us" class="last">Contact <br /><span class="tagline">We're listening</span></a>
          <ul>
            <li><a href="support.htm" title="Need help?">Support</a></li>*@
          </ul>
        @*</li>
      </ul>*@
    </nav>
  </header>
  <section id="actionCall">
      @if (IsSectionDefined("header"))
      {
          @RenderSection("header",false)
      } else
      {
       <br/><br/>
      }
  </section>
  <div id="contentWrapper">
      <section id="mainContent">
          @RenderBody()
      </section>
     

      <aside id="secondaryContent">
          @if (IsSectionDefined("secondaryContent"))
          {
              @RenderSection("secondaryContent", false)
          } else
          {
              <div id="specials" class="callOut">
                  @await (Component.InvokeAsync<ProEmbV4.ViewComponents.UsedModelsViewComponent>())
                  <br /><br/>
              </div>
          }
         
      </aside>
  </div>
  <footer id="pageFooter">
  <section id="quickLinks">
  <h1>Quick Nav</h1>
    <ul id="quickNav">
      <li><a href="/" title="Our home page">Home</a></li>
      <li><a href="@Url.Action("GetAllItems","DynamoDB")" title="Temperatuur via LoraWan">Temperatuur</a></li>
      <li><a href="@Url.Action("Webcam","Webcam")" title="Webcam">Webcam</a></li>
      @*<li><a href="resources.htm" title="Relais">Relais</a></li>
      <li><a href="explorers.htm" title="PLACEHOLDER">PLACEHOLDER</a></li>
      <li><a href="contact.htm" title="Contact and support">Contact</a></li>*@
    </ul>
  </section>
  @*<section id="footerResources">*@
  @*<h1>Resources</h1>
    <ul id="quickNav">*@
      @*<li><a href="resources/faq.htm" title="Our home page">FAQ</a></li>*@
      @*<li><a href="support.htm" title="Need help?">Support</a></li>*@
      @*<li><a href="resources/legal.htm" title="The fine print">Legal</a></li>*@
      @*<li><a href="login.htm">Login</a></li>
    </ul>*@
  @*</section>*@
  <section id="companyInfo">
  <h1>Contact</h1>
  <h2>Laurens & Michiel 2IC </h2>
  <p>
      Doorniksesteenweg 145<br />
      Kortrijk 8500 @DateTime.Now.Year
  </p>
  </section>
  </footer>
</div>
</body>
</html>

ProEmbV4/Views/Shared/_Post.cshtml
@inject ProEmbV4.Models.FormattingService Format
@model ProEmbV4.Models.Post


<article class="blog-post">
    <h1>@Model.Title</h1>
    <div class="details">
        Posted <span>@Format.AsReadableDate(Model.Posted)</span> by <span>@Model.Author</span>
    </div>
    <div class="content">
        @Model.Body
    </div>
</article>

ProEmbV4/Views/Shared/_SimpleLayout.cshtml
@{
    Layout = "_Layout";
}
@section secondaryContent
{}

@RenderBody()

ProEmbV4/Views/Webcam/webcam.cshtml
@{
    Layout = "_Layout";
}

<h1>Webcam</h1>
 <iframe src="http://192.168.137.35:8081/" width="700" height="500" frameborder="0"></iframe>